on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: usha1.azurecr.io
        username: ${{ secrets.acr_usha1_username }}
        password: ${{ secrets.acr_usha1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t usha1.azurecr.io/usha:1 --label dockerfile-path=Dockerfile
        docker push usha1.azurecr.io/usha:1
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vehan1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: usha1.azurecr.io
        container-registry-username: ${{ secrets.acr_usha1_username }}
        container-registry-password: ${{ secrets.acr_usha1_password }}
        secret-name: vehan1dockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: repo
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:usha1.azurecr.io/usha
          image.tag:1
          imagePullSecrets:
            -name:vehan1dockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          usha1.azurecr.io/usha:1
        imagepullsecrets: |
          vehan1dockerauth
